[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rothschild_capital = "CKisbvKYZ2Ft9Pwbs5MxbEdbUaRpSNYBcMJuca5heB3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./rtc_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]

